# -*- coding: utf-8 -*-
"""Tugas_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zu02qreGozrVE62N0VQ2_4njP67koxwg

# POISSON
"""

import pandas as pd
from math import factorial, exp

def probablititas(x, miu = 1):
  poisson= ((miu**x) * exp(-miu)) / factorial(x)
  return poisson

def poison(n, p, miu = 1):
  hasil = (miu/n) * p
  return hasil

print("=======================")
print("Inputan Untuk Poison")
print("=======================")
miu = 5
print('miu = ',miu)
n = 11
print('n   = ',n)
print("=======================")

pj = []
pj.append(probablititas(0, miu))

fj = []
fj.append(sum(pj))

for i in range(1, n):
  pj.append(poison(i, pj[-1], miu))
  fj.append(sum(pj))

d = {'p':pj,'F':fj}
df = pd.DataFrame(d)
print(df)
print("")

def random(a, m, c, x0, n):
	x = []
	x.append(x0)
	for i in range(n):
		rand = (a * x[i] + c) % m
		x.append(rand)
	return x

print("=======================")
print("Inputan Untuk Random")
print("=======================")
a = 7
print('a   = ',a)
m = 99
print('m   = ',m)
c = 6
print('c   = ',c)
x0 = 3
print('x0  = ',x0)
n = 11
print('n   = ',n)
print("=======================")
print("")

xi = random(a, m, c, x0, n)
U = [(i/m) for i in xi]

hasil = []

for i in range(len(U)):
	for j in range(len(fj)):
		if U[i] < fj[j]:
			hasil.append(j)
			break

import pandas as pd

d = {'x[i]':xi,'U[i]':U, 'p[i]':hasil}
df = pd.DataFrame(d)
print(df)
